'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import RevisionXml, {type Revision} from './RevisionXml'
import SelectorReferencias from './SelectorReferencias'
import styles from './registro.module.css'
type Orden={descripcion:string;creado_en:string;id:string;numero:string;saldo_por_facturar:number;estado_facturacion:string}
type Documento={id:string;numero:string;fecha:string;posiciones:Posicion[]}
type Posicion={posicion_id?:string;documento_linea_id?:string;documento?:string;documento_posicion?:string;orden_id:string;pedido:string;id:string;numero:string;material:string;tipo?:'material'|'servicio';codigo_servicio?:string|null;paquete_servicio?:string|null;numero_servicio?:string|null;requiere_aceptacion_servicio?:boolean;descripcion:string;unidad:string;cantidad_pendiente:number;precio_unitario:number;tasa_igv:number;saldo:number}
type Asignacion={posicion_id:string;cantidad:string;linea_xml?:number}
type ConfigRegistro={ruc_proveedor:string;sociedades_receptoras:{ruc:string;razon_social:string;codigo_sap:string}[]}
const api='http://localhost:8000'
const headers=()=>({Authorization:`Bearer ${localStorage.getItem('access_token')||''}`})
async function respuesta(r:Response){const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'No se pudo procesar la solicitud.');return d}
const initial={serie:'',correlativo:'',fecha_emision:'',moneda:'PEN',ruc_emisor:'',ruc_receptor:'',monto_subtotal:'',monto_igv:'',monto_total:''}
export default function NuevaFactura(){
 const [base,setBase]=useState('pedido');const [documentos,setDocumentos]=useState<Documento[]>([]);const [seleccionDocs,setSeleccionDocs]=useState<string[]>([]);const [cargandoDocs,setCargandoDocs]=useState(false)
 const [validada,setValidada]=useState('');const [validando,setValidando]=useState(false);const [configRegistro,setConfigRegistro]=useState<ConfigRegistro|null>(null)
 const router=useRouter();const version=useRef(0)
 const [ordenes,setOrdenes]=useState<Orden[]>([]);const [orden,setOrden]=useState('');const [pedidos,setPedidos]=useState<string[]>([]);const [modo,setModo]=useState('xml')
 const [posiciones,setPosiciones]=useState<Posicion[]>([]);const [bloqueo,setBloqueo]=useState('Selecciona un pedido.');const [asignaciones,setAsignaciones]=useState<Asignacion[]>([])
 const [xml,setXml]=useState<File|null>(null);const [pdf,setPdf]=useState<File|null>(null);const [revision,setRevision]=useState<Revision|null>(null)
 const [manual,setManual]=useState(initial);const [error,setError]=useState('');const [leyendo,setLeyendo]=useState(false);const [enviando,setEnviando]=useState(false);const [recarga,setRecarga]=useState(0)
 useEffect(()=>{const c=new AbortController();fetch(`${api}/ordenes`,{headers:headers(),signal:c.signal}).then(respuesta).then((d:Orden[])=>{setOrdenes(d.filter(o=>['pendiente','parcial'].includes(o.estado_facturacion)));const id=new URLSearchParams(window.location.search).get('orden')||'';setOrden(id);setPedidos(id?[id]:[])}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[recarga])
 useEffect(()=>{const c=new AbortController();fetch(`${api}/facturas/configuracion-registro`,{headers:headers(),signal:c.signal}).then(respuesta).then((d:ConfigRegistro)=>{if(c.signal.aborted)return;setConfigRegistro(d);setManual(prev=>({...prev,ruc_emisor:d.ruc_proveedor,ruc_receptor:prev.ruc_receptor||(d.sociedades_receptoras.length===1?d.sociedades_receptoras[0].ruc:'')}))}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[])
 useEffect(()=>{if(!['pedido','pedido_completo'].includes(base)||!pedidos.length)return;const c=new AbortController();Promise.all(pedidos.map(async id=>{const d=await respuesta(await fetch(`${api}/ordenes/${id}/posiciones`,{headers:headers(),signal:c.signal}));return {id,...d}})).then(results=>{setPosiciones(results.flatMap(d=>d.posiciones.map((p:Posicion)=>({...p,orden_id:d.id,pedido:ordenes.find(o=>o.id===d.id)?.numero||d.id}))));setBloqueo(results.filter(d=>d.bloqueo).map(d=>`${ordenes.find(o=>o.id===d.id)?.numero}: ${d.bloqueo}`).join(' '))}).catch(e=>{if(!c.signal.aborted){setError(e.message);setBloqueo('No se pudieron cargar las posiciones.')}});return()=>c.abort()},[pedidos,ordenes,base])
 useEffect(()=>{if(['pedido','pedido_completo'].includes(base))return;const c=new AbortController();fetch(`${api}/documentos-base?tipo=${base}`,{headers:headers(),signal:c.signal}).then(respuesta).then((d:Documento[])=>{if(!c.signal.aborted)setDocumentos(d)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setCargandoDocs(false)});return()=>c.abort()},[base,recarga])
 function cambiarBase(value:string){setBase(value);setPedidos([]);setOrden('');setPosiciones([]);setAsignaciones([]);setDocumentos([]);setSeleccionDocs([]);setBloqueo('Selecciona referencias para facturar.');setCargandoDocs(!['pedido','pedido_completo'].includes(value))}
 function cambiarDocumentos(ids:string[]){setSeleccionDocs(ids);const rows=documentos.filter(d=>ids.includes(d.id)).flatMap(d=>d.posiciones);const orders=[...new Set(rows.map(p=>p.orden_id))];setPedidos(orders);setOrden(orders[0]||'');setPosiciones(rows);setAsignaciones([]);setBloqueo(rows.length?'':'Selecciona documentos con cantidades pendientes.')}
 async function leer(file:File|null,pedido=orden,receptor=manual.ruc_receptor){const v=++version.current;setXml(file);setRevision(null);setAsignaciones([]);setError('');setLeyendo(false);if(!file)return;if(file.size>5242880){setError('XML: máximo 5 MB.');return}if(!receptor){setError('Selecciona la sociedad receptora antes de revisar el XML.');return}setLeyendo(true);const form=new FormData();form.append('xml',file);form.append('orden_compra_id',pedido);form.append('multipedido','true');form.append('ruc_receptor',receptor);try{const d=await respuesta(await fetch(`${api}/facturas/previsualizar`,{method:'POST',headers:headers(),body:form}));if(v===version.current)setRevision(d)}catch(e){if(v===version.current)setError(e instanceof Error?e.message:'Error al leer XML.')}finally{if(v===version.current)setLeyendo(false)}}
 function cambiarReceptor(ruc:string){setManual(prev=>({...prev,ruc_receptor:ruc}));setValidada('');setRevision(null);if(xml&&modo==='xml')leer(xml,orden,ruc)}
 function cambiarPedidos(ids:string[]){setPedidos(ids);setOrden(ids[0]||'');setPosiciones([]);setAsignaciones([]);setBloqueo(ids.length?'Cargando posiciones…':'Selecciona uno o varios pedidos.');if(xml&&modo==='xml')leer(xml,ids[0]||'')}
 function asignar(pid:string,cantidad:string,index?:number){setAsignaciones(prev=>[...prev.filter(a=>index===undefined?a.posicion_id!==pid:a.linea_xml!==index),...(pid&&(seleccionCompleta||Number(cantidad)>0)?[{posicion_id:pid,cantidad,linea_xml:index}]:[])])}
 const seleccionCompleta=base==='pedido_completo'
 const automaticas:Asignacion[]=[]
 if(seleccionCompleta&&modo==='xml'&&revision){
  for(const [i,l] of revision.lineas.entries()){
   const candidatos=posiciones.filter(p=>p.tipo!=='servicio'&&p.cantidad_pendiente>0&&(!l['Pedido']||l['Pedido']===p.pedido)&&(!l['Posición pedido']||l['Posición pedido'].replace(/^0+/,'')===p.numero.replace(/^0+/,''))&&(l['Código']?l['Código']===p.material:l['Descripción'].trim().toLocaleLowerCase()===p.descripcion.trim().toLocaleLowerCase())&&l['Unidad']===p.unidad&&Number(l['Valor unitario'])===p.precio_unitario&&Number(l['Cantidad'])>0&&Number(l['Cantidad'])<=p.cantidad_pendiente)
   if(candidatos.length===1)automaticas.push({posicion_id:candidatos[0].id,cantidad:l['Cantidad'],linea_xml:i})
  }
 }
 const asignacionesActivas=seleccionCompleta&&modo==='pdf'?posiciones.filter(p=>p.tipo!=='servicio'&&p.cantidad_pendiente>0).map(p=>({posicion_id:p.id,cantidad:asignaciones.find(a=>a.posicion_id===p.id)?.cantidad??String(p.cantidad_pendiente),linea_xml:undefined})).filter(a=>Number(a.cantidad)>0):seleccionCompleta?automaticas:asignaciones
 const calculadas=asignacionesActivas.map(a=>{const p=posiciones.find(p=>p.id===a.posicion_id);const net=p?Math.round(Number(a.cantidad)*p.precio_unitario*100)/100:0;const tax=p?Math.round(net*p.tasa_igv)/100:0;return {a,p,net,tax,total:net+tax}})
 const subtotal=calculadas.reduce((s,l)=>s+l.net,0);const impuestos=calculadas.reduce((s,l)=>s+l.tax,0);const total=Math.round((subtotal+impuestos)*100)/100
 const saldo=ordenes.filter(o=>pedidos.includes(o.id)).reduce((s,o)=>s+o.saldo_por_facturar,0)
 const problemas=calculadas.flatMap(l=>{if(!l.p)return ['Posición inválida.'];const errors=[];if(Number(l.a.cantidad)>l.p.cantidad_pendiente)errors.push(`Cantidad superior al pendiente de ${l.p.numero}.`);if(l.total>l.p.saldo+.001)errors.push(`Saldo insuficiente en ${l.p.numero}.`);if(l.p.tipo==='servicio'&&!l.p.documento_linea_id)errors.push(`Selecciona una hoja de entrada de servicios aceptada para ${l.p.numero}.`);if(modo==='xml'&&revision&&l.a.linea_xml!==undefined){const x=revision.lineas[l.a.linea_xml];const code=l.p.tipo==='servicio'?l.p.codigo_servicio:l.p.material;if(x&&(Number(x['Valor unitario'])!==l.p.precio_unitario||Math.abs(Number(x['Valor de venta'])-l.net)>.001||Math.abs(Number(x['Impuestos']||0)-l.tax)>.001||x['Unidad']!==l.p.unidad||(x['Código']&&code&&x['Código']!==code)))errors.push(`La línea XML no coincide con código de material/servicio, unidad, precio o importe de ${l.p.numero}.`)}return errors})
 if(new Set(asignacionesActivas.map(a=>a.posicion_id)).size!==asignacionesActivas.length)problemas.push('Una posición no puede repetirse en este registro.')
 if(modo==='xml'&&revision&&asignacionesActivas.length!==revision.lineas.length)problemas.push(seleccionCompleta?'No se pudo relacionar automáticamente todo el XML con los pedidos. Revisa las referencias y materiales del XML o utiliza Pedido / posición para asignarlos.':'Asigna todas las líneas XML.')
 if(seleccionCompleta&&posiciones.some(p=>p.tipo==='servicio'&&p.cantidad_pendiente>0))problemas.push('Este pedido incluye servicios. Registra las posiciones de material por pedido y factura los servicios aparte, seleccionando su hoja de entrada de servicios aceptada.')
 for(const oid of pedidos){const aplicado=calculadas.filter(l=>l.p?.orden_id===oid).reduce((s,l)=>s+l.total,0);const o=ordenes.find(o=>o.id===oid);if(o&&aplicado>o.saldo_por_facturar+.001)problemas.push('Saldo insuficiente en pedido '+o.numero+'.')}
 if(total>saldo+.001)problemas.push('El importe supera el saldo del pedido.')
 if(modo==='pdf'&&asignacionesActivas.length&&[Math.abs(Number(manual.monto_subtotal)-subtotal),Math.abs(Number(manual.monto_igv)-impuestos),Math.abs(Number(manual.monto_total)-total)].some(v=>v>.001))problemas.push('Los importes ingresados deben coincidir con las posiciones seleccionadas.')
 if(modo==='xml'&&revision&&Math.abs(Number(revision.totales['Importe a pagar'])-total)>.001)problemas.push('El importe del XML no coincide con la selección.')
 if(seleccionCompleta){for(const oid of pedidos){if(!calculadas.some(l=>l.p?.orden_id===oid&&Number(l.a.cantidad)>0)){const nombre=ordenes.find(o=>o.id===oid)?.numero||oid;problemas.push('Incluye al menos una posición de '+nombre+'.')}}} 
 const mostrarErroresValidacion=modo==='xml'?Boolean(revision):Boolean(pdf)
 const camposPdfRequeridos=['serie','correlativo','fecha_emision','monto_subtotal','monto_igv','monto_total'] as const
 const camposPdfIncompletos=modo==='pdf'&&camposPdfRequeridos.some(campo=>!manual[campo].trim())
 const sociedadSeleccionada=Boolean(configRegistro?.sociedades_receptoras.some(s=>s.ruc===manual.ruc_receptor))
 const apto=Boolean(orden&&pdf&&!bloqueo&&asignacionesActivas.length&&!problemas.length&&!leyendo&&sociedadSeleccionada&&(modo==='pdf'?!camposPdfIncompletos:Boolean(xml&&revision?.puede_enviar)))
 const razonesBloqueo=[
  ...(!orden?['Selecciona al menos un pedido o documento de referencia.']:[]),
  ...(bloqueo?[bloqueo]:[]),
  ...(!pdf?['Adjunta el PDF de la factura; es obligatorio en ambas modalidades.']:[]),
  ...(!configRegistro?['Cargando las sociedades habilitadas para recibir facturas.']:[]),
  ...(configRegistro&&!sociedadSeleccionada?['Selecciona una sociedad receptora habilitada.']:[]),
  ...(modo==='xml'&&!xml?['Adjunta el XML de la factura.']:[]),
  ...(leyendo?['Espera a que termine la lectura del XML.']:[]),
  ...(modo==='xml'&&xml&&!revision&&!leyendo?['No hay una revisión válida del XML. Revisa el error mostrado arriba y vuelve a cargarlo.']:[]),
  ...(modo==='xml'&&revision&&!revision.puede_enviar?revision.validaciones.filter(v=>v.estado==='error').map(v=>`${v.campo}: ${v.detalle}`):[]),
  ...(camposPdfIncompletos?['Completa serie, número, fecha, subtotal, IGV y total. El RUC del emisor viene de tu usuario; selecciona la sociedad receptora.']:[]),
  ...(!asignacionesActivas.length?['Selecciona posiciones y cantidades que se incluirán en la factura.']:[]),
  ...problemas,
 ].filter((motivo,i,lista)=>Boolean(motivo)&&lista.indexOf(motivo)===i)
 const firma=JSON.stringify({asignaciones:asignacionesActivas,modo,manual,pedidos,base,xml:xml?[xml.name,xml.size,xml.lastModified]:null,pdf:pdf?[pdf.name,pdf.size,pdf.lastModified]:null,revision})
 async function procesar(solo:boolean){if(!apto||enviando||validando||(!solo&&validada!==firma))return;if(solo){setValidando(true)}else{setEnviando(true)}setError('');const form=new FormData();form.append('orden_compra_id',orden);form.append('modo',modo);form.append('asignaciones',JSON.stringify(asignacionesActivas.map(a=>{const p=posiciones.find(p=>p.id===a.posicion_id);return {...a,posicion_id:p?.posicion_id||a.posicion_id,documento_linea_id:p?.documento_linea_id,cantidad:Number(a.cantidad)}})));form.append('cabecera',JSON.stringify({...manual,base_facturacion:base,pedidos_completos:seleccionCompleta?pedidos:[]}));form.append('pdf',pdf!);if(modo==='xml'&&xml)form.append('xml',xml);try{const d=await respuesta(await fetch(`${api}/facturas/registrar-posiciones${solo?'?validar_solo=true':''}`,{method:'POST',headers:headers(),body:form}));if(solo)setValidada(firma);else router.push(`/dashboard/facturas/${d.id}`)}catch(e){setValidada('');setError(e instanceof Error?e.message:'No se pudo procesar la factura.')}finally{setValidando(false);setEnviando(false)}}
 return <div className={styles.page}><Link href="/dashboard/facturas">← Facturas</Link><h1>Registrar factura</h1><p>Registra una factura contra pedidos completos, posiciones o documentos de referencia.</p>{error&&<div role="alert" className={styles.error}>{error}<button type="button" onClick={()=>{setError('');setRecarga(v=>v+1)}}>Actualizar pedidos</button></div>}
 <form onSubmit={e=>{e.preventDefault();procesar(false)}}><fieldset disabled={enviando||validando}>
 <section><h2>1. Base de facturación y referencias</h2><div className={styles.grid}><label>RUC del proveedor (usuario)<input value={configRegistro?.ruc_proveedor||''} readOnly aria-readonly="true"/></label><label>Sociedad receptora<select required value={manual.ruc_receptor} onChange={e=>cambiarReceptor(e.target.value)}><option value="">Selecciona la sociedad</option>{configRegistro?.sociedades_receptoras.map(s=><option key={s.ruc} value={s.ruc}>{s.razon_social} · RUC {s.ruc}{s.codigo_sap?` · SAP ${s.codigo_sap}`:''}</option>)}</select></label></div><p>El RUC del proveedor se toma de tu usuario. Selecciona la sociedad a la que va dirigida la factura; el RUC no se escribe manualmente.</p><label>Facturar contra<select value={base} onChange={e=>cambiarBase(e.target.value)}><option value="pedido">Pedido / posición</option><option value="pedido_completo">Pedido(s) · posiciones pendientes</option><option value="mercancia">Ingreso de mercancía</option><option value="servicio">Aceptación de servicio</option><option value="guia">Guía de remisión</option></select></label><p>{base==='pedido_completo'?<>Selecciona uno o varios pedidos; se mostrarán sus posiciones pendientes. {modo==='pdf'?'En PDF puedes ajustar la cantidad que incluirás en la factura.':'Con XML, las cantidades se toman de la factura y se validan contra el saldo de cada posición.'}</>:base==='mercancia'?'Solo cantidades recibidas y pendientes de facturar.':base==='servicio'?'Solo cantidades de servicios aceptados y pendientes de facturar.':base==='guia'?'Cantidades despachadas en la guía; no equivale a aceptación de mercancía.':'Selecciona posiciones de uno o varios pedidos.'} Los filtros conservan tu selección.{!seleccionCompleta&&' Cambiar las referencias requiere volver a asignar cantidades.'}</p>
{['pedido','pedido_completo'].includes(base)?<SelectorReferencias pedidosCompletos={seleccionCompleta} items={ordenes.map(o=>({id:o.id,numero:o.numero,detalle:o.descripcion||'',fecha:o.creado_en,saldo:o.saldo_por_facturar}))} selected={pedidos} onChange={cambiarPedidos} label={seleccionCompleta?"Seleccionar pedidos":"Buscar pedidos"}/>:cargandoDocs?<p role="status">Cargando documentos…</p>:<SelectorReferencias key={base} items={documentos.map(d=>({id:d.id,numero:d.numero,fecha:d.fecha,detalle:[...new Set(d.posiciones.map(p=>p.pedido+' · '+p.descripcion))].join(' / ')}))} selected={seleccionDocs} onChange={cambiarDocumentos} label="Buscar documentos y pedidos"/>}
<div aria-live="polite">{seleccionCompleta&&<p><strong>{pedidos.length} pedido(s) seleccionado(s) · Total pendiente a facturar: S/ {saldo.toFixed(2)}</strong></p>}</div><div className={styles.grid}><label>Forma de registro<select value={modo} onChange={e=>{version.current++;setModo(e.target.value);setRevision(null);setXml(null);setAsignaciones([]);setLeyendo(false)}}><option value="xml">XML + PDF · lectura automática</option><option value="pdf">Solo PDF · ingreso manual</option></select></label></div></section>
 <section><h2>2. Documentos</h2><div className={styles.grid}>{modo==='xml'&&<label>XML · máximo 5 MB<input key={modo} type="file" accept=".xml" required onChange={e=>leer(e.target.files?.[0]||null)}/></label>}<label>PDF · máximo 5 MB<input type="file" accept=".pdf" required onChange={e=>{const f=e.target.files?.[0]||null;setPdf(f&&f.size<=5242880?f:null);if(f&&f.size>5242880)setError('PDF: máximo 5 MB.')}}/></label></div>{leyendo&&<p role="status">Leyendo XML…</p>}</section>
 {modo==='xml'&&revision&&<section><h2>Datos completados desde el XML</h2><div className={styles.grid}>{Object.entries({Serie:revision.cabecera.Comprobante?.split('-')[0]||'',Número:revision.cabecera.Comprobante?.split('-').slice(1).join('-')||'',Fecha:revision.cabecera['Fecha de emisión'],'RUC emisor':revision.emisor.Documento,'RUC receptor':revision.receptor.Documento,Moneda:revision.cabecera.Moneda,'Total XML':revision.totales['Importe a pagar']}).map(([k,v])=><label key={k}>{k}<input readOnly value={v||'No informado'}/></label>)}</div></section>}
 {modo==='pdf'&&<section><h2>Datos de la factura PDF</h2><p>Transcribe los datos del documento. No se extraen automáticamente del PDF. Los RUC se completan desde tu usuario y la sociedad seleccionada.</p><div className={styles.grid}>{Object.entries({serie:'Serie',correlativo:'Número',fecha_emision:'Fecha de emisión',moneda:'Moneda',monto_subtotal:'Subtotal',monto_igv:'IGV',monto_total:'Total'}).map(([key,label])=><label key={key}>{label}<input required readOnly={key==='moneda'} type={key==='fecha_emision'?'date':key.startsWith('monto')?'number':'text'} step={key.startsWith('monto')?'0.01':undefined} min={key.startsWith('monto')?'0':undefined} value={manual[key as keyof typeof manual]} onChange={e=>setManual({...manual,[key]:e.target.value})}/></label>)}</div></section>}
 <section><h2>3. Posiciones y cantidades por pedido</h2>{bloqueo&&<p role="status">{bloqueo}</p>}{!pedidos.length&&!['mercancia','servicio','guia'].includes(base)&&<p>Selecciona uno o varios pedidos para ver sus posiciones.</p>}{posiciones.some(p=>p.tipo==='servicio')&&<p role="note">Las líneas de servicio mantienen la referencia al paquete y sublínea del pedido. Para facturarlas, selecciona “Aceptación de servicio” y usa una hoja aceptada; las líneas sin aceptación no se pueden enviar.</p>}<div className={styles.tableWrap}><table><thead><tr>{!seleccionCompleta&&<th>Documento base</th>}<th>Pedido</th><th>Tipo / posición SAP</th><th>Material / servicio</th><th>Descripción</th><th>Unidad</th><th>Cantidad pendiente</th><th>Precio sin IGV</th><th>IGV %</th><th>Saldo pendiente</th><th>Cantidad a facturar</th><th>Importe a facturar</th></tr></thead><tbody>{posiciones.map(p=>{const asignada=asignacionesActivas.find(a=>a.posicion_id===p.id);const qty=Number(asignada?.cantidad||0);const net=Math.round(qty*p.precio_unitario*100)/100;const tax=Math.round(net*p.tasa_igv)/100;const codigo=p.tipo==='servicio'?p.codigo_servicio||'Servicio':p.material;return <tr key={p.id}>{!seleccionCompleta&&<td>{p.documento||"Pedido"}{p.documento_posicion&&` / ${p.documento_posicion}`}</td>}<td>{p.pedido}</td><td>{p.tipo==='servicio'?`${p.numero} / servicio ${p.numero_servicio||''}`:p.numero}</td><td>{codigo}{p.tipo==='servicio'&&p.paquete_servicio?` · paquete ${p.paquete_servicio}`:''}</td><td>{p.descripcion}</td><td>{p.unidad}</td><td>{p.cantidad_pendiente}</td><td>{p.precio_unitario.toFixed(2)}</td><td>{p.tasa_igv}</td><td>{p.saldo.toFixed(2)}</td><td><input aria-label={`Cantidad a facturar ${p.tipo==='servicio'?'servicio':'posición'} ${p.numero}`} type="number" min="0.0001" max={p.cantidad_pendiente} step="0.0001" readOnly={modo==='xml'} disabled={Boolean(bloqueo)||p.cantidad_pendiente===0||p.tipo==='servicio'&&!p.documento_linea_id||seleccionCompleta&&modo==='xml'} value={asignada?.cantidad||''} placeholder={modo==='pdf'&&seleccionCompleta&&!asignaciones.some(a=>a.posicion_id===p.id)?String(p.cantidad_pendiente):''} onChange={e=>asignar(p.id,e.target.value)}/></td><td>S/ {(net+tax).toFixed(2)}</td></tr>})}</tbody></table></div>{seleccionCompleta&&<><p>El máximo por posición es su cantidad pendiente. Si facturas menos, el saldo restante seguirá disponible para otra factura.</p><p><strong>Subtotal S/ {subtotal.toFixed(2)} · IGV S/ {impuestos.toFixed(2)} · Total a facturar S/ {total.toFixed(2)} · Saldo pendiente de pedidos S/ {Math.max(saldo-total,0).toFixed(2)}</strong></p></>}
 {!seleccionCompleta&&modo==='xml'&&revision&&<><h2>Relaciona cada línea XML con su posición</h2>{revision.lineas.map((l,i)=><label key={i}>Línea {l['Ítem']} · {l['Descripción']} · Cantidad {l['Cantidad']} · Neto {l['Valor de venta']}<select required value={asignaciones.find(a=>a.linea_xml===i)?.posicion_id||''} onChange={e=>asignar(e.target.value,l['Cantidad'],i)}><option value="">Selecciona una posición</option>{posiciones.filter(p=>p.tipo!=='servicio'||Boolean(p.documento_linea_id)).map(p=><option key={p.id} value={p.id}>{p.documento ? p.documento+" / " : ""}{p.pedido} / {p.numero}{p.tipo==='servicio'?` · servicio ${p.numero_servicio||''} · ${p.codigo_servicio||'Servicio'}`:` · ${p.material}`} · {p.descripcion}</option>)}</select></label>)}</>}
 {!seleccionCompleta&&<><p><strong>Selección: subtotal S/ {subtotal.toFixed(2)} · IGV S/ {impuestos.toFixed(2)} · Total S/ {total.toFixed(2)}</strong></p><p>Saldo conjunto de los pedidos después del registro: S/ {(saldo-total).toFixed(2)} · {total>0&&total<saldo?'Facturación parcial':total>0?'Completa el saldo de los pedidos':''}</p></>}{mostrarErroresValidacion&&problemas.length>0&&<ul role="alert" className={styles.error}>{problemas.map((p,i)=><li key={i}>{p}</li>)}</ul>}</section>
 {modo==='xml'&&revision&&<RevisionXml revision={revision}/>}
 {!seleccionCompleta&&<section><h2>Resumen por pedido</h2>{pedidos.map(id=>{const o=ordenes.find(o=>o.id===id);const monto=calculadas.filter(l=>l.p?.orden_id===id).reduce((s,l)=>s+l.total,0);return <p key={id}><strong>{o?.numero}</strong> · A facturar S/ {monto.toFixed(2)} · Saldo posterior S/ {((o?.saldo_por_facturar||0)-monto).toFixed(2)}</p>})}</section>}
 <section><h2>Validación y envío</h2>{error&&<div role="alert" className={styles.error}>{error}</div>}{!apto&&<div role="status" className={styles.readiness}><strong>Completa estos pasos para habilitar la validación:</strong><ul>{razonesBloqueo.map((motivo,i)=><li key={`${i}-${motivo}`}>{motivo}</li>)}</ul></div>}{apto&&validada!==firma&&<p role="status">Primero selecciona “Validar factura”. Si cambias un dato o archivo después, vuelve a validarla antes de guardar.</p>}{validada===firma&&<p role="status">✓ Factura validada contra los pedidos y documentos seleccionados. Los saldos se volverán a comprobar al guardar.</p>}<p>Integración preparada para SAP ECC, S/4HANA y S/4HANA Cloud Public Edition (GROW). El envío a SAP estará disponible cuando se configure la interfaz de tu empresa.</p><div className={styles.pagination}><button type="button" disabled={!apto||enviando||validando} onClick={()=>procesar(true)}>{validando?'Validando…':'Validar factura'}</button><button type="submit" className={styles.primary} disabled={!apto||validada!==firma||enviando||validando}>{enviando?'Guardando…':'Guardar factura validada'}</button><button type="button" disabled title="Falta configurar la conexión SAP">Enviar a SAP · pendiente de conexión</button></div><p>Guardar reserva las cantidades y deja la factura pendiente de integración. Todavía no crea un documento en SAP.</p></section></fieldset></form></div>
}







