'use client'
import {useState} from 'react'
import styles from './registro.module.css'
export type Referencia={id:string;numero:string;detalle:string;fecha?:string;saldo?:number}
export default function SelectorReferencias({items,selected,onChange,label,pedidosCompletos=false}:{items:Referencia[];selected:string[];onChange:(ids:string[])=>void;label:string;pedidosCompletos?:boolean}){
 const [q,setQ]=useState('');const [desde,setDesde]=useState('');const [hasta,setHasta]=useState('');const [pagina,setPagina]=useState(1);const [solo,setSolo]=useState(false)
 const invalid=Boolean(desde&&hasta&&desde>hasta)
 const matches=invalid?[]:items.filter(i=>(i.numero+' '+i.detalle).toLocaleLowerCase('es').includes(q.trim().toLocaleLowerCase('es'))&&(!desde||(i.fecha||'').slice(0,10)>=desde)&&(!hasta||Boolean(i.fecha&&i.fecha.slice(0,10)<=hasta))&&(!solo||selected.includes(i.id)))
 const filtrados=new Set(matches.map(i=>i.id))
 const todosFiltrados=matches.length>0&&matches.every(i=>selected.includes(i.id))
 const pages=Math.max(1,Math.ceil(matches.length/10));const actual=Math.min(pagina,pages);const rows=matches.slice((actual-1)*10,actual*10)
 return <div className={styles.selector}><h2>{label}</h2><div className={styles.grid}><label>Buscar número, pedido o descripción<input type="search" value={q} placeholder={pedidosCompletos?"Ej.: DEMO-OC-2026-0001":"Ej.: POS-0001 o EM-2026"} onChange={e=>{setQ(e.target.value);setPagina(1)}}/></label><label>Desde<input type="date" value={desde} onChange={e=>{setDesde(e.target.value);setPagina(1)}}/></label><label>Hasta<input type="date" value={hasta} onChange={e=>{setHasta(e.target.value);setPagina(1)}}/></label></div>
 <label className={styles.orderCheck}><input type="checkbox" checked={solo} onChange={e=>{setSolo(e.target.checked);setPagina(1)}}/>Solo seleccionados</label>
 {invalid&&<p role="alert">Corrige el rango de fechas.</p>}<p aria-live="polite">{matches.length} resultados · {selected.length} seleccionados</p>
 {pedidosCompletos&&<><p>Un check incluye todo el saldo pendiente del pedido, con todas sus posiciones.</p><div className={styles.pagination}><button type="button" disabled={!matches.length||todosFiltrados} onClick={()=>onChange([...new Set([...selected,...filtrados])])}>Seleccionar todos los pedidos filtrados ({matches.length})</button><button type="button" disabled={!selected.some(id=>filtrados.has(id))} onClick={()=>onChange(selected.filter(id=>!filtrados.has(id)))}>Quitar pedidos filtrados</button><button type="button" disabled={!selected.length} onClick={()=>onChange([])}>Vaciar selección</button></div><p>La selección incluye los resultados de todas las páginas. Cambiar los filtros conserva los pedidos marcados.</p></>}
 <div className={styles.chips}>{selected.map(id=><button key={id} type="button" onClick={()=>onChange(selected.filter(v=>v!==id))} aria-label={`Quitar ${items.find(i=>i.id===id)?.numero||id}`}>{items.find(i=>i.id===id)?.numero||id} ×</button>)}</div>
 {pedidosCompletos?<div className={styles.tableWrap}><table><thead><tr><th>Seleccionar</th><th>Número de pedido</th><th>Fecha del pedido</th><th>Saldo total a facturar</th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><input type="checkbox" aria-label={`Seleccionar pedido completo ${i.numero}`} checked={selected.includes(i.id)} onChange={e=>onChange(e.target.checked?[...selected,i.id]:selected.filter(v=>v!==i.id))}/></td><td><strong>{i.numero}</strong></td><td>{i.fecha?.slice(0,10)||'—'}</td><td>S/ {(i.saldo||0).toFixed(2)}</td></tr>)}</tbody><tfoot><tr><th colSpan={3}>Total de los {selected.length} pedidos seleccionados</th><td><strong>S/ {items.filter(i=>selected.includes(i.id)).reduce((sum,i)=>sum+(i.saldo||0),0).toFixed(2)}</strong></td></tr></tfoot></table></div>:rows.map(i=><label key={i.id} className={styles.orderCheck}><input type="checkbox" checked={selected.includes(i.id)} onChange={e=>onChange(e.target.checked?[...selected,i.id]:selected.filter(v=>v!==i.id))}/><span><strong>{i.numero}</strong>{i.saldo!==undefined&&` · S/ ${i.saldo.toFixed(2)}`}<small className={styles.referenceDetail}>{i.detalle}{i.fecha&&` · ${i.fecha.slice(0,10)}`}</small></span></label>)}
 {!rows.length&&<p>No hay resultados con estos filtros.</p>}<div className={styles.pagination}><button type="button" disabled={actual<=1} onClick={()=>setPagina(actual-1)}>Anterior</button><span>Página {actual} de {pages}</span><button type="button" disabled={actual>=pages} onClick={()=>setPagina(actual+1)}>Siguiente</button><button type="button" onClick={()=>{setQ('');setDesde('');setHasta('');setSolo(false);setPagina(1)}}>Limpiar filtros</button></div>
 </div>
}
